<?php/**
 * @var $block \Mod\PriceView\Block\PriceView
 */

?>


<div>
<?php
//колхоз
    $view = [
          'Base Price'         => $this->basePrice(),
          'Tier Price'         => $this->tierPrice(),
          'final Price'        => $this->finalPrice(),
          'special Price'      => $this->specialPrice(),
          'catalog rule Price' => $this->catalogRulePrice(),
    ];
    $count = 0;
?>
    <?php foreach ($view as $key => $item): ?>
    <?php if ($item) : ?>
    <p><span style="font-weight: bolder; border-bottom: 2px solid <?=$block->colorize()[$count]?>"><?=$key?></span> : <?=$item?></p>
    <?php endif; ?>
    <?php $count++; ($count > (count($block->colorize())-1) && ($count = 0)); ?>
    <?php endforeach;?>
</div>
