<?php
/**
 * @var $block \Mod\PriceView\Block\PriceView
 */

/**
 *

 */
?>


<div>
<?php
    $colorize = ['0077c2','#00bcd4','#dce775','#f57f17','#90a4ae'];
    $count = 0;
?>
    <?php if ($block->basePrice()): ?>
        <p><span style="font-weight: bolder; border-bottom: 2px solid <?=$colorize[$count++]?>">base price :</span> <?=$block->basePrice()?></p>
    <?php endif; ?>

    <?php if ($block->tierPrice()): ?>
        <p><span style="font-weight: bolder; border-bottom: 2px solid <?=$colorize[$count++]?>">tier price :</span> <?=($block->tierPrice());?></p>
    <?php endif; ?>

    <?php if ($block->finalPrice()): ?>
        <p><span style="font-weight: bolder; border-bottom: 2px solid <?=$colorize[$count++]?>">final price :</span> <?=$block->finalPrice();?></p>
    <?php endif; ?>

    <?php if ($block->specialPrice()): ?>
        <p><span style="font-weight: bolder; border-bottom: 2px solid <?=$colorize[$count++]?>">special price :</span> <?=$block->specialPrice();?></p>
    <?php endif; ?>

    <?php if ($block->catalogRulePrice()): ?>
        <p><span style="font-weight: bolder; border-bottom: 2px solid <?=$colorize[$count++]?>">catalog rule price:</span> <?=$block->catalogRulePrice();?></p>
    <?php endif; ?>
</div>
