<?php

namespace Mod\Categorical\Model\Attribute\Backend;

use Magento\Eav\Model\Entity\Attribute\Backend\AbstractBackend;

class Categorical extends AbstractBackend
{
    public function validate($object)
    {
        return parent::validate($object); // TODO: Change the autogenerated stub
    }
}
